services:
  web:
    container_name: gabtic17
    build:
      context: .
      dockerfile: odoo.Dockerfile
    command: odoo --dev xml 
    depends_on:
      - db
    ports:
      - 7001:8069
    volumes:
      - ./home/odoo/.local/share/Odoo:/var/lib/odoo
      - ./config:/etc/odoo
      - /home/ashmxwy/Desktop/TDS/Odoo17/industries/:/mnt/extra-addons
      - /home/ashmxwy/Desktop/TDS/Odoo17/addons:/mnt/enterprise
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
    restart: "always"
    stdin_open: true
    tty: true

  db:
    container_name: gabtic17_db
    build:
      context: .
      dockerfile: postgres.Dockerfile
    ports:
      - 4001:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - POSTGRES_DB=postgres
    restart: "always"
